package com.dappon.app.webservice.hr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-17T11:57:25.938+08:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "AppServiceService", 
                  wsdlLocation = "http://10.224.72.20:8080/eos-default/AppService?wsdl",
                  targetNamespace = "http://www.primeton.com/AppService") 
public class AppServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.primeton.com/AppService", "AppServiceService");
    public final static QName AppServicePort = new QName("http://www.primeton.com/AppService", "AppServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.224.72.20:8080/eos-default/AppService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AppServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.224.72.20:8080/eos-default/AppService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AppServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AppServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AppService
     */
    @WebEndpoint(name = "AppServicePort")
    public AppService getAppServicePort() {
        return super.getPort(AppServicePort, AppService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppService
     */
    @WebEndpoint(name = "AppServicePort")
    public AppService getAppServicePort(WebServiceFeature... features) {
        return super.getPort(AppServicePort, AppService.class, features);
    }

}
