package com.dappon.app.webservice.hr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-17T11:57:25.926+08:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://www.primeton.com/AppService", name = "AppService")
@XmlSeeAlso({ObjectFactory.class})
public interface AppService {

    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/AppService")
    @RequestWrapper(localName = "getCourier", targetNamespace = "http://www.primeton.com/AppService", className = "com.dappon.app.webservice.hr.GetCourier")
    @WebMethod
    @ResponseWrapper(localName = "getCourierResponse", targetNamespace = "http://www.primeton.com/AppService", className = "com.dappon.app.webservice.hr.GetCourierResponse")
    public com.dappon.app.webservice.hr.Courier getCourier(
        @WebParam(name = "in0", targetNamespace = "http://www.primeton.com/AppService")
        java.lang.String in0
    );
}
