
package com.dappon.app.webservice.hr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.io.FileOutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.commons.io.FileUtils;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-17T11:57:25.862+08:00
 * Generated source version: 2.4.6
 * 
 */
public final class AppService_AppServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.primeton.com/AppService", "AppServiceService");

    private AppService_AppServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AppServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AppServiceService ss = new AppServiceService(wsdlURL, SERVICE_NAME);
        AppService port = ss.getAppServicePort();  
        
        {
        System.out.println("Invoking getCourier...");
        java.lang.String _getCourier_in0 = "149175";
        com.dappon.app.webservice.hr.Courier _getCourier__return = port.getCourier(_getCourier_in0);
        System.out.println("getCourier.result=" + _getCourier__return);
        byte[] buffer = _getCourier__return.getPhoto().getValue();

     
        FileUtils.writeByteArrayToFile(new File("d:/a.jpg"), buffer);
        }

        System.exit(0);
    }

}
